Avoid needless `std::mem::replace`
In Rust 1.45.0, `std::mem::replace` gained the `#[must_use]` attribute,
causing a new diagnostic for some `bindgen` code :

    error: unused return value of `std::mem::replace` that must be used
       --> src/ir/comp.rs:751:17
        |
    751 | /                 mem::replace(
    752 | |                     self,
    753 | |                     CompFields::AfterComputingBitfieldUnits {
    754 | |                         fields,
    755 | |                         has_bitfield_units,
    756 | |                     },
    757 | |                 );
        | |__________________^
        |
        = note: `-D unused-must-use` implied by `-D warnings`
        = note: if you don't need the old value, you can just assign the new value directly

    error: unused return value of `std::mem::replace` that must be used
       --> src/ir/comp.rs:760:17
        |
    760 |                 mem::replace(self, CompFields::ErrorComputingBitfieldUnits);
        |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        |
        = note: if you don't need the old value, you can just assign the new value directly

    error: aborting due to 2 previous errors